image: node:14-slim
tasks:
  - init: yarn install
    command: yarn serve
ports:
  - port: 3000
    onOpen: open-preview
github:
  prebuilds:
    master: true

vscode:
  extensions:
    - robole.markdown-snippets@0.6.0:qq4J4xA9fQWqoYzOMxooPA==
    - ban.spellright@3.0.56:YwD4WJevKAZNKRwbc5b7QA==